language: node_js
node_js:
  - "11.10.0"
cache:
  - npm
before_script:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build  
  - now --token=$ZEIT_KEY -e SECRET_BOT_KEY=$SECRET_BOT_KEY